
// Graphics
#macro RESOLUTION_W 320
#macro RESOLUTION_H 180
#macro FRAME_RATE 60
#macro OUT 0
#macro IN 1
#macro TRANSITION_SPEED 0.04
#macro TRANSITION_OFFSET 20
#macro FLASH_DURATION 0.5
#macro FLASH_DECAY 0.04
#macro CARRY_HEIGHT 13

// Text
#macro T_STROKE 8
#macro T_ISTROKE 1
#macro TEXT_BOX_HEIGHT 70
#macro DEFAULT_TBG_FRAME 1

// Instances
#macro INTERACTION_DISTANCE 10
#macro INTERACTION_RADIUS 4
#macro BOUNCE_HEIGHT_FALLOFF 0.6
#macro DEFAULT_THROW_DISTANCE 52
#macro THROW_SPEED 3
#macro THROW_GRAVITY 0.1

// Enemies
#macro ENEMY_WANDER_RADIUS 32
#macro ENEMY_DEFAULT_SPEED 0.35
#macro DEFAULT_ENEMY_WAIT_DUR 120
#macro DEFAULT_ENEMY_AGGRO 5
#macro ENEMY_DEFAULT_RADIUS 48
#macro ENEMY_DEFAULT_ATTACK_RADIUS 16
#macro ENEMY_ATTACK_OFFSET 8
#macro DEFAULT_ENEMY_STATE_WAIT_DURATION 15

// Hard Numbers
#macro MAX 9999
#macro MIN -9999
#macro PROGRESS_PERCENTAGE_ZERO 0
#macro PROGRESS_PERCENTAGE_ONE 1
#macro EOF -1
#macro NULL 0
#macro HALF 0.5

// Geometric
#macro CARDINAL_DIR round(direction/90)
#macro FULL_CIRCLE 360
#macro RIGHT_ANGLE 90
#macro HALF_ANGLE 45

// Miscellanous
#macro TILE_SIZE 16
#macro ROOM_START rVillage
#macro CAM_OFF 15
#macro ATTEMPT 2

// Enums

enum ENEMYSTATE
{
	IDLE,
	WANDER,
	CHASE,
	ATTACK,
	HURT,
	DIE,
	WAIT,
	COUNT // HAS TO BE LAST
}

